version: '3.4'

services:
  stem-robot.web:
    image: ${DOCKER_REGISTRY-}stemrobotweb
    build:
      context: .
      dockerfile: STEM-ROBOT_BE/Dockerfile
    ports:
      - "5000:5000" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always

    